
create table if not exists person
(
    person_id  integer generated by default as identity
        primary key,
    name       varchar(100) not null,
    year_birth integer
        constraint person_year_birth_check
            check (year_birth > 1600)
);

create table if not exists book
(
    book_id        integer generated by default as identity
        primary key,
    person_id      integer
                                references person
                                    on delete set null,
    name_book      varchar(100) not null,
    name_author    varchar(100) not null,
    year_written   integer
        constraint book_year_written_check
            check (year_written > 1600),
    date_of_person timestamp
);
